[project]
name = "fastlbp"
authors = [
  { name = "Dmytro Horyslavets", email = "nepotlet@gmail.com" }, 
  { name = "Mykhailo Koreshkov", email = "koreshov.m@gmail.com" }
]
maintainers = [
  { name="Dmytro Horyslavets", email="nepotlet@gmail.com" }
]
description = "fastLBP: parallelised and GPU-powered multi-radii Local Binary Patterns computation"
keywords = ["local binary patterns", "visual descriptor", "computer vision", "image processing", "parallel"]
readme = "README.md"
requires-python = ">=3.11, <3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Development Status :: 4 - Beta",
  "Operating System :: POSIX",
  "Operating System :: POSIX :: Linux",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Bio-Informatics"
]

dependencies = [
  "wheel",
  "scikit-image>=0.22.0",
  "numpy>=1.26.0",
  "Pillow>=10.0.1",
  "pandas>=2.1.1",
  "psutil"
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/imbg-ua/fastLBP"
"Bug Tracker" = "https://github.com/imbg-ua/fastLBP/issues"

[build-system]
requires = ["setuptools>=61.0", "numpy", "cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "fastlbp.__version__"}
